from langchain_groq import ChatGroq
import streamlit as st
from dotenv import load_dotenv  
from langchain_core.prompts import PromptTemplate, SystemMessagePromptTemplate, HumanMessagePromptTemplate,load_prompt
load_dotenv()
st.header('Research Assistant')
# user_input=st.text_input("enter your text here...")
paper_input=st.selectbox("Select a paper", ["Attention Is All You Need", "Generative Pre-trained Transformer", "About ddos attacks"])
style_input=st.selectbox("Select a explanation style", ["Beginner friendly", "Technical", "Code oriented", "Mathematical"])
length_input=st.selectbox("Select a length", ["Short (1-2 paragraph)", "Medium (3-4 paragraphs)", "Long (1-2 pages)"])

# Define the prompt template with placeholders for the user inputs
# template=PromptTemplate(
#     template="Explain the paper '{paper}' in a {style} style and {length} length. include all the relevant content  and also use the relateble anologies to simplyfy the complex ideas. make sure to cover all the important points and provide a comprehensive understanding of the paper.",
#     input_variables=["paper", "style", "length"]
# )
template=load_prompt("template.json")
#prompt is the final prompt that will be sent to the model, it is generated by filling in the template with the user inputs
prompt=template.invoke({"paper": paper_input, "style": style_input, "length": length_input})

# Display the generated prompt to the user
if st.button("submit"):
    chat=ChatGroq(model="llama-3.3-70b-versatile", 
              temperature=0.9,
              )
    response = chat.invoke(prompt)
    st.write("AI response:", response.content)
